import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import net.proteanit.sql.DbUtils;


public class AdminListPanel {
    private JPanel panel1;
    private JButton searchForButton;
    private JButton addNewButton;
    private JButton modifyButton;
    private JButton deleteButton;
    private JTable table1;
    private JLabel label1;
    private JButton refreshButton;
    private String table;
    private String name;

    public AdminListPanel(String t, String n) {
        this(t, n, "*");
    }
    public AdminListPanel(String t, String n, String c) {
        this.table = t;
        this.name = n;
        searchForButton.setText("Search for " + name);
        addNewButton.setText("Add New " + name);
        modifyButton.setText("Modify " + name);
        deleteButton.setText("Delete " + name);
        {
            searchForButton.addActionListener(e -> UserFrame.openSearch("Search for " + name));
            addNewButton.addActionListener(e -> UserFrame.openSearch("Add New " + name));
            modifyButton.addActionListener(e -> UserFrame.openSearch("Modify " + name));
            deleteButton.addActionListener(e -> UserFrame.openSearch("Delete " + name));
        }

        refreshButton.addActionListener(e -> {
            SwingWorker s = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    table1.setVisible(false);
                    label1.setText("Searching for " + name + "s...");
                    refreshButton.setEnabled(false);
                    searchForButton.setEnabled(false);
                    addNewButton.setEnabled(false);
                    modifyButton.setEnabled(false);
                    deleteButton.setEnabled(false);
                    DatabaseManager db = new DatabaseManager();
                    table1.setModel(DbUtils.resultSetToTableModel(db.selectTable(table, c)));
                    return null;
                }

                @Override
                protected void done() {
                    table1.setVisible(true);
                    label1.setText("List of all " + name + "s:");
                    refreshButton.setEnabled(true);
                    searchForButton.setEnabled(true);
                    addNewButton.setEnabled(true);
                    modifyButton.setEnabled(true);
                    deleteButton.setEnabled(true);
                }
            };
            s.execute();
        });

        refreshButton.doClick();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.NORTH);
        refreshButton = new JButton();
        refreshButton.setText("Refresh");
        panel3.add(refreshButton, BorderLayout.EAST);
        label1 = new JLabel();
        label1.setHorizontalAlignment(2);
        label1.setText("   List of all ");
        panel3.add(label1, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel2.add(panel4, BorderLayout.SOUTH);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.NORTH);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        panel5.add(panel6, BorderLayout.WEST);
        searchForButton = new JButton();
        searchForButton.setText("Search for ");
        panel6.add(searchForButton, BorderLayout.EAST);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel5.add(panel7, BorderLayout.EAST);
        addNewButton = new JButton();
        addNewButton.setText("Add new ");
        panel7.add(addNewButton, BorderLayout.EAST);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new BorderLayout(0, 0));
        panel4.add(panel8, BorderLayout.SOUTH);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new BorderLayout(0, 0));
        panel8.add(panel9, BorderLayout.WEST);
        modifyButton = new JButton();
        modifyButton.setText("Modify ");
        panel9.add(modifyButton, BorderLayout.NORTH);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel8.add(panel10, BorderLayout.EAST);
        deleteButton = new JButton();
        deleteButton.setText("Delete ");
        panel10.add(deleteButton, BorderLayout.EAST);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, BorderLayout.CENTER);
        table1 = new JTable();
        table1.setEnabled(false);
        table1.setUpdateSelectionOnSort(true);
        scrollPane1.setViewportView(table1);
        final JLabel label2 = new JLabel();
        label2.setText("    ");
        panel1.add(label2, BorderLayout.EAST);
        final JLabel label3 = new JLabel();
        label3.setText("    ");
        panel1.add(label3, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
