import javax.swing.*;
import java.awt.*;
import net.proteanit.sql.DbUtils;


public class ListPanel {
    private JPanel panel1;
    private JButton searchForXButton;
    private JButton addNewXButton;
    private JButton modifyXButton;
    private JButton deleteXButton;
    private JTable table1;

    public ListPanel() {
        DatabaseManager db = new DatabaseManager();
        table1.setModel(DbUtils.resultSetToTableModel(db.connectionTest()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(2);
        label1.setText("   List of all X:");
        panel2.add(label1, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.SOUTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, BorderLayout.NORTH);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.WEST);
        searchForXButton = new JButton();
        searchForXButton.setText("Search for X");
        panel5.add(searchForXButton, BorderLayout.EAST);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        panel4.add(panel6, BorderLayout.EAST);
        addNewXButton = new JButton();
        addNewXButton.setText("Add new X");
        panel6.add(addNewXButton, BorderLayout.EAST);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel3.add(panel7, BorderLayout.SOUTH);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new BorderLayout(0, 0));
        panel7.add(panel8, BorderLayout.WEST);
        modifyXButton = new JButton();
        modifyXButton.setText("Modify X");
        panel8.add(modifyXButton, BorderLayout.NORTH);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new BorderLayout(0, 0));
        panel7.add(panel9, BorderLayout.EAST);
        deleteXButton = new JButton();
        deleteXButton.setText("Delete X");
        panel9.add(deleteXButton, BorderLayout.EAST);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        table1 = new JTable();
        table1.setEnabled(false);
        table1.setUpdateSelectionOnSort(true);
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
