import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;

public class SessionWindow {
    private JPanel panel1;
    private JTextArea courseIDText;
    private JTextArea courseFieldText;
    private JTextArea contactHoursText;
    private JTextArea courseCostText;
    private JTextArea courseNameText;
    private JTextArea sessionName;
    private JTextArea sessionHours;
    private JTextArea dayOfWeek;
    private JTextArea location;

    public JComponent getUI() {
        return this.$$$getRootComponent$$$();
    }

    public SessionWindow(String sessionNo) {

        SwingWorker s = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                try {
                    DatabaseManager db = new DatabaseManager();
                    ResultSet rs = db.selectTable("((course " +
                            "RIGHT JOIN training_session ON course.CourseId = training_session.CourseID) " +
                            "RIGHT JOIN sessionhours ON sessionhours.SessionNumber = training_session.SessionID) " +
                            "RIGHT JOIN schedule_time ON schedule_time.SessionNumber = training_session.SessionID " +
                            "WHERE SessionID = " + sessionNo + ";");
                    rs.next();
                    courseIDText.setText(rs.getString("CourseId"));
                    courseFieldText.setText(rs.getString("field"));
                    courseNameText.setText(rs.getString("CourseName"));
                    contactHoursText.setText(rs.getString("contentHourse"));
                    courseCostText.setText(rs.getString("cost"));
                    sessionName.setText(rs.getString("SessionName"));
                    sessionHours.setText(rs.getString("StartT") + " to " + rs.getString("EndT"));
                    dayOfWeek.setText(rs.getString("DayOfweek"));
                    location.setText(rs.getString("Location"));

                } catch (SQLException s) {
                    JOptionPane.showMessageDialog(null, s.getStackTrace(), s.getMessage(), JOptionPane.WARNING_MESSAGE);
                }
                return null;
            }
        };

        s.execute();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("   ");
        panel2.add(label1, BorderLayout.EAST);
        final JLabel label2 = new JLabel();
        label2.setText("   ");
        panel2.add(label2, BorderLayout.WEST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, BorderLayout.NORTH);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.WEST);
        final JLabel label3 = new JLabel();
        label3.setText("Course ID");
        panel5.add(label3, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        panel4.add(panel6, BorderLayout.EAST);
        courseIDText = new JTextArea();
        courseIDText.setColumns(25);
        courseIDText.setEditable(false);
        courseIDText.setEnabled(true);
        courseIDText.setText("Please wait...");
        panel6.add(courseIDText, BorderLayout.EAST);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel3.add(panel7, BorderLayout.CENTER);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new BorderLayout(0, 0));
        panel7.add(panel8, BorderLayout.NORTH);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new BorderLayout(0, 0));
        panel8.add(panel9, BorderLayout.WEST);
        final JLabel label4 = new JLabel();
        label4.setText("Course Name");
        panel9.add(label4, BorderLayout.CENTER);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel8.add(panel10, BorderLayout.EAST);
        courseNameText = new JTextArea();
        courseNameText.setColumns(25);
        courseNameText.setEditable(false);
        courseNameText.setEnabled(true);
        courseNameText.setText("Please wait...");
        panel10.add(courseNameText, BorderLayout.EAST);
        final JPanel panel11 = new JPanel();
        panel11.setLayout(new BorderLayout(0, 0));
        panel7.add(panel11, BorderLayout.CENTER);
        final JPanel panel12 = new JPanel();
        panel12.setLayout(new BorderLayout(0, 0));
        panel11.add(panel12, BorderLayout.NORTH);
        final JPanel panel13 = new JPanel();
        panel13.setLayout(new BorderLayout(0, 0));
        panel12.add(panel13, BorderLayout.WEST);
        final JLabel label5 = new JLabel();
        label5.setText("Course Cost");
        panel13.add(label5, BorderLayout.CENTER);
        final JPanel panel14 = new JPanel();
        panel14.setLayout(new BorderLayout(0, 0));
        panel12.add(panel14, BorderLayout.EAST);
        courseCostText = new JTextArea();
        courseCostText.setColumns(25);
        courseCostText.setEditable(false);
        courseCostText.setText("Please wait...");
        panel14.add(courseCostText, BorderLayout.EAST);
        final JPanel panel15 = new JPanel();
        panel15.setLayout(new BorderLayout(0, 0));
        panel11.add(panel15, BorderLayout.CENTER);
        final JPanel panel16 = new JPanel();
        panel16.setLayout(new BorderLayout(0, 0));
        panel15.add(panel16, BorderLayout.NORTH);
        final JPanel panel17 = new JPanel();
        panel17.setLayout(new BorderLayout(0, 0));
        panel16.add(panel17, BorderLayout.WEST);
        final JLabel label6 = new JLabel();
        label6.setText("Contact Hours");
        panel17.add(label6, BorderLayout.CENTER);
        final JPanel panel18 = new JPanel();
        panel18.setLayout(new BorderLayout(0, 0));
        panel16.add(panel18, BorderLayout.EAST);
        contactHoursText = new JTextArea();
        contactHoursText.setColumns(25);
        contactHoursText.setEditable(false);
        contactHoursText.setText("Please wait...");
        panel18.add(contactHoursText, BorderLayout.EAST);
        final JPanel panel19 = new JPanel();
        panel19.setLayout(new BorderLayout(0, 0));
        panel15.add(panel19, BorderLayout.CENTER);
        final JPanel panel20 = new JPanel();
        panel20.setLayout(new BorderLayout(0, 0));
        panel19.add(panel20, BorderLayout.NORTH);
        final JPanel panel21 = new JPanel();
        panel21.setLayout(new BorderLayout(0, 0));
        panel20.add(panel21, BorderLayout.WEST);
        final JLabel label7 = new JLabel();
        label7.setText("Course's Field");
        panel21.add(label7, BorderLayout.CENTER);
        final JPanel panel22 = new JPanel();
        panel22.setLayout(new BorderLayout(0, 0));
        panel20.add(panel22, BorderLayout.EAST);
        courseFieldText = new JTextArea();
        courseFieldText.setColumns(25);
        courseFieldText.setEditable(false);
        courseFieldText.setText("Please wait...");
        panel22.add(courseFieldText, BorderLayout.EAST);
        final JLabel label8 = new JLabel();
        label8.setText(" ");
        panel19.add(label8, BorderLayout.SOUTH);
        final JPanel panel23 = new JPanel();
        panel23.setLayout(new BorderLayout(0, 0));
        panel19.add(panel23, BorderLayout.CENTER);
        final JLabel label9 = new JLabel();
        label9.setText(" ");
        panel23.add(label9, BorderLayout.NORTH);
        final JPanel panel24 = new JPanel();
        panel24.setLayout(new BorderLayout(0, 0));
        panel23.add(panel24, BorderLayout.CENTER);
        final JPanel panel25 = new JPanel();
        panel25.setLayout(new BorderLayout(0, 0));
        panel24.add(panel25, BorderLayout.NORTH);
        final JPanel panel26 = new JPanel();
        panel26.setLayout(new BorderLayout(0, 0));
        panel25.add(panel26, BorderLayout.WEST);
        final JLabel label10 = new JLabel();
        label10.setText("Session Name");
        panel26.add(label10, BorderLayout.CENTER);
        final JPanel panel27 = new JPanel();
        panel27.setLayout(new BorderLayout(0, 0));
        panel25.add(panel27, BorderLayout.EAST);
        sessionName = new JTextArea();
        sessionName.setColumns(25);
        sessionName.setEditable(false);
        sessionName.setText("Please wait...");
        panel27.add(sessionName, BorderLayout.EAST);
        final JPanel panel28 = new JPanel();
        panel28.setLayout(new BorderLayout(0, 0));
        panel24.add(panel28, BorderLayout.CENTER);
        final JPanel panel29 = new JPanel();
        panel29.setLayout(new BorderLayout(0, 0));
        panel28.add(panel29, BorderLayout.NORTH);
        final JPanel panel30 = new JPanel();
        panel30.setLayout(new BorderLayout(0, 0));
        panel29.add(panel30, BorderLayout.WEST);
        final JLabel label11 = new JLabel();
        label11.setText("Session Hours");
        panel30.add(label11, BorderLayout.CENTER);
        final JPanel panel31 = new JPanel();
        panel31.setLayout(new BorderLayout(0, 0));
        panel29.add(panel31, BorderLayout.EAST);
        sessionHours = new JTextArea();
        sessionHours.setColumns(25);
        sessionHours.setEditable(false);
        sessionHours.setText("Please wait...");
        panel31.add(sessionHours, BorderLayout.EAST);
        final JPanel panel32 = new JPanel();
        panel32.setLayout(new BorderLayout(0, 0));
        panel28.add(panel32, BorderLayout.CENTER);
        final JPanel panel33 = new JPanel();
        panel33.setLayout(new BorderLayout(0, 0));
        panel32.add(panel33, BorderLayout.NORTH);
        final JPanel panel34 = new JPanel();
        panel34.setLayout(new BorderLayout(0, 0));
        panel33.add(panel34, BorderLayout.WEST);
        final JLabel label12 = new JLabel();
        label12.setText("Day of Week");
        panel34.add(label12, BorderLayout.CENTER);
        final JPanel panel35 = new JPanel();
        panel35.setLayout(new BorderLayout(0, 0));
        panel33.add(panel35, BorderLayout.EAST);
        dayOfWeek = new JTextArea();
        dayOfWeek.setColumns(25);
        dayOfWeek.setEditable(false);
        dayOfWeek.setText("Please wait...");
        panel35.add(dayOfWeek, BorderLayout.EAST);
        final JPanel panel36 = new JPanel();
        panel36.setLayout(new BorderLayout(0, 0));
        panel32.add(panel36, BorderLayout.CENTER);
        final JPanel panel37 = new JPanel();
        panel37.setLayout(new BorderLayout(0, 0));
        panel36.add(panel37, BorderLayout.NORTH);
        final JPanel panel38 = new JPanel();
        panel38.setLayout(new BorderLayout(0, 0));
        panel37.add(panel38, BorderLayout.WEST);
        final JLabel label13 = new JLabel();
        label13.setText("Location");
        panel38.add(label13, BorderLayout.CENTER);
        final JPanel panel39 = new JPanel();
        panel39.setLayout(new BorderLayout(0, 0));
        panel37.add(panel39, BorderLayout.EAST);
        location = new JTextArea();
        location.setColumns(25);
        location.setEditable(false);
        location.setText("Please wait...");
        panel39.add(location, BorderLayout.EAST);
        final JLabel label14 = new JLabel();
        label14.setText(" ");
        panel1.add(label14, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
