import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;

public class UserListPanel {
    private JPanel panel1;
    private JPanel SessionList;

    public UserListPanel(int traineeID) {
        try {
            DatabaseManager db = new DatabaseManager();
            ResultSet rs = db.selectTable("is_enrolled WHERE traineeID = " + traineeID + ";");
            while (rs.next()) {
                SessionList.add(new SessionButton(rs.getString("SessionNumber")));
            }
        } catch (SQLException s) {
            JOptionPane.showMessageDialog(null, s.getStackTrace(), s.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("                    ");
        panel2.add(label1, BorderLayout.EAST);
        final JLabel label2 = new JLabel();
        label2.setText("                    ");
        panel2.add(label2, BorderLayout.WEST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.CENTER);
        final JLabel label3 = new JLabel();
        label3.setText(" ");
        panel3.add(label3, BorderLayout.NORTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, BorderLayout.CENTER);
        final JLabel label4 = new JLabel();
        label4.setText("Your courses:");
        panel4.add(label4, BorderLayout.NORTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel4.add(scrollPane1, BorderLayout.CENTER);
        SessionList = new JPanel();
        SessionList.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        scrollPane1.setViewportView(SessionList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
